services:
  mongo:
    image: mongo:latest
    container_name: media-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: media_pipeline
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: media-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  server:
    build:
      context: ./
      dockerfile: server/Dockerfile
    container_name: media-api
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/media_pipeline?authSource=admin
      - REDIS_HOST=redis
      - NOTIFICATION_SERVICE_URL=http://notification:5005
    volumes:
      - ./server:/app/server
      - /app/server/node_modules

  worker:
    build:
      context: ./
      dockerfile: worker/Dockerfile
    container_name: media-worker
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ./worker/.env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/media_pipeline?authSource=admin
      - REDIS_HOST=redis
      - GOOGLE_APPLICATION_CREDENTIALS=/app/worker/ai-image-pipeline-499705-ef60bce44cf2.json
    volumes:
      - ./worker:/app/worker
      - /app/worker/node_modules

  notification:
    build:
      context: ./
      dockerfile: notification/Dockerfile
    container_name: media-notification
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - ./notification/.env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/media_pipeline?authSource=admin
      - REDIS_HOST=redis
    volumes:
      - ./notification:/app/notification
      - /app/notification/node_modules

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    container_name: media-frontend
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

volumes:
  mongo_data:
  redis_data: